project:
  type: website
  preview:
    port: 5550
    browser: false
    watch-inputs: true
    navigate: false

website:
  title: "󰙔 &nbsp; Algorithmology"
  search:
    location: navbar
    type: textbox
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "icons/microscope.svg"
  open-graph: true
  site-url: https://www.algorithmology.org/
  repo-url: https://github.com/Algorithmology/www.algorithmology.org
  issue-url: https://github.com/Algorithmology/www.algorithmology.org/issues/new
  repo-actions: [source, edit, issue]
  repo-branch: "master"
  navbar:
    right:
      - about.qmd
      - presentations/index.qmd

format:
  html:
    mainfont: Inter
    monofont: Ubuntu Mono
    fontsize: 1.25em
    theme: zephyr

execute:
  freeze: auto
