project:
  type: website
  preview:
    port: 5550
    browser: false
    watch-inputs: true
    navigate: false

website:
  title: "{{< iconify uis microscope size=30px >}} &nbsp; Algorithmology"
  search:
    location: navbar
    type: textbox
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "icons/microscope.svg"
  open-graph: true
  site-url: https://www.algorithmology.org/
  repo-url: https://github.com/Algorithmology/www.algorithmology.org
  navbar:
    right:
      - syllabus/index.qmd
      - schedule/index.qmd
      - slides/index.qmd

  page-footer:
    left: '<a href="https://github.com/Algorithmology/www.algorithmology.org/graphs/contributors" aria-label="Algorithmology Maintainers">{{< iconify fa copyright >}} Algorithmology</a>'
    right:
      - text: "{{< iconify fa github size=18px >}}"
        href: https://github.com/Algorithmology/
      - text: "{{< iconify fa github-square size=18px >}}"
        href: https://github.com/Algorithmology/www.algorithmology.org/
      - text: "{{< iconify bi discord size=19px >}}"
        href: https://discord.gg/YHjhQaBnme
      - text: "{{< iconify bi rss-fill size=18px >}}"
        href: "blog/index.xml"

format:
  html:
    mainfont: Inter
    monofont: Ubuntu Mono
    fontsize: 1.25em
    theme: zephyr
    css: css/styles.css

execute:
  freeze: auto
