---
title: All-Hands
layout: full
toc: true
listing:
  - id: featured-posts
    type: default
    sort-ui: true
    filter-ui: true
    fields: [author,date,title]
    contents:
      - "week*/**/*.qmd"
    sort:
      - "date desc"
      - "title"
---

Interesting in learning more about how to use experimental and analytical
techniques to study algorithms and data structures? To learn more, checkout
these articles from the [Algorithm All-Hands projects](../syllabus/index.qmd) in
which a team of learners explores the efficiency of a software system
implemented in Python! Each article reports details about the efficiency of
specific algorithms and data structures in connection to chapters in the book [A
First Course on Data Structures in
Python](https://donsheehy.github.io/datastructures/). Make sure to review the
[course schedule](../schedule/index.qmd) for more details about how these
algorithm all-hands reports connect other course components. While these reports
are not guaranteed to be correct, they should show the growth of a learner as
they develop their knowledge and skills in the field of algorithm engineering.

:::{#featured-posts}
:::
