---
title: Software Testing
description: "Establish Confidence in Program Correctness"
date: 2025-02-03
layout: full
toc: true
toc-expand: 3
---

## Exploration

- {{< iconify fa6-solid book-open size=18px >}} Read chapter 4 of [A First
Course on Data Structures in
Python](https://donsheehy.github.io/datastructures/)
- {{< iconify fa6-brands github size=18px >}} Study `test` for the `ds2` package
of [donsheehy/datastructures](https://github.com/donsheehy/datastructures/)

## Activities

- {{< iconify fa6-solid people-line size=18px >}} **Tuesday and Thursday**:
Software Testing
  - Understand why algorithm engineers must test programs
  - Discern the differences between benchmarking and testing
  - Explore the benefits and limitations of testing
  - Investigate different approaches to software testing
  - Understand performance trade-offs with software testing
  - Examine source code segments to illustrate trade-offs
- {{< iconify fa6-solid diagram-project size=18px >}} **Friday**: Submit
algorithm engineering project two, start algorithm engineering project three,
and take the second algorithm engineering skill-check in the second half of the
laboratory session.

## Project

### Goal

To build and use a Python program, called `objectprocessing`, that runs
benchmarks to study the performance of storing and searching for objects using
three different ways for determining whether or not a search term matches the
value in an object's attributes.

### Steps

- Click the link provided in Discord to get started on this project
- Reference {{< iconify fa6-brands github size=18px >}} [Object
Processing](https://github.com/Algorithmology/object-processing-starter) as a
public reference repository
- Install the project's dependencies using `devenv` and/or `poetry`
- Follow the instructions to complete the project:
  - **Week 1**: Implement all of the modules in `objectprocessing`
  - **Week 2**: Design, conduct, and document experimental results
- Schedule [office hours](https://www.gregorykapfhammer.com/schedule/) if you
have questions

::: {.callout-note appearance="minimal" title="Student Insights" collapse="false"}
Students who completed this project shared these insights:

- "Object processing can be a challenging task! But it is useful when
determining overheads for how fast different search approaches are going to be
in Python. It allows us to manipulate different variables of the approach to
determine the fastest way to search through a database." **Keller Liptrap**

- "This experiment taught me how to properly organize and search through large
data files using an object-oriented approach. This project taught me how
efficient these systems can be when handling larger data sets." **Sabrina
Rodriguez**

:::

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekfour/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week Four: Software Testing](../../slides/weekfour/)
