---
title: Stacks, Queues, and Deques
description: "Explore Basic Abstract Data Types"
date: 2025-02-22
layout: full
toc: true
toc-expand: 3
---

## Exploration

- {{< iconify fa6-solid book-open size=18px >}} Read chapters 6 and 7 in [A
First Course on Data Structures in
Python](https://donsheehy.github.io/datastructures/)
- {{< iconify fa6-brands github size=18px >}} Try out the implementations of
`Stack`, `Queue`, and `Deque` in the `ds2` package of
[donsheehy/datastructures](https://github.com/donsheehy/datastructures/). Can
you write your own tests cases for these data structures? Can you use these
data structures in your own program?
- {{< iconify fa6-solid book size=18px >}} Note that, along with chapter 8,
chapter 7 will again be the focus for next week

## Activities

- {{< iconify fa6-solid people-line size=18px >}} **Monday and Wednesday**:
Stacks, Queues, and Deques
  - Explore the concept of an abstract data type (ADT)
  - Understand implementation trade-offs for stacks, queues, and deques
  - Use asymptotic analysis to characterize performance of an ADT
  - Enhance an ADT implementation with useful exception handling
  - Examine Python source code segments to illustrate key points
- {{< iconify fa6-solid diagram-project size=18px >}} **Thursday**: Continue algorithm engineering project
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Planning for next algorithm all-hands project

## Project

### Goal

To build and use a Python program, called `filesorter`, that runs benchmarks to
study the performance of sorting different types of data stored in a CSV file.

### Steps

- Use [File Sorting](https://github.com/Algorithmology/file-sorting-starter) as your template repository
- Install the project's dependencies using `devenv`
- Follow the instructions to complete the project:
  - **Week 1**: Implement all of the modules in `filesorter`
  - **Week 2**: Design and conduct experiments and document experimental results
- Schedule [office hours](https://www.gregorykapfhammer.com/schedule/) if you
have questions

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekseven/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week Seven: Implementing Stack, Queues, and Deques](../../slides/weekseven/)
