---
title: Runtime Analysis
description: "Characterize Performance with Experiments"
date: 2025-02-10
layout: full
toc: true
toc-expand: 3
---

## Exploration

- {{< iconify fa6-solid book-open size=18px >}} Read chapter 5 of [A First
Course on Data Structures in
Python](https://donsheehy.github.io/datastructures/)
- {{< iconify fa6-brands github size=18px >}} Experimentally evaluate
performance of algorithms, data structures, and systems in the `ds2` package of
[donsheehy/datastructures](https://github.com/donsheehy/datastructures/)
- {{< iconify fa6-solid book size=18px >}} Note that next week's focus will also be on running time analysis!

## Activities

- {{< iconify fa6-solid people-line size=18px >}} **Monday and Wednesday**:
Empirical Evaluation
  - Understand why program performance is critically important
  - Characterize performance patterns in Python programs
  - Use experimentation to characterize performance trade-offs
  - Prepare for using asymptotic analysis to characterize performance
  - Examine source code segments to illustrate key points
- {{< iconify fa6-solid diagram-project size=18px >}} **Thursday**: Continue algorithm engineering project
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Presentations during algorithm all-hands session

## Project

### Goal

To build and use a Python program, called `objectprocessing`, that runs
benchmarks to study the performance of storing and searching for objects using
three different ways for determining whether or not a search term matches the
value in an object's attributes.

### Steps

- Use [Object Processing](https://github.com/Algorithmology/object-processing-starter) as your template repository
- Install the project's dependencies using `devenv`
- Follow the instructions to complete the project:
  - **Week 1**: Implement all of the modules in `objectprocessing`
  - **Week 2**: Design and conduct experiments and document experimental results
- Schedule [office hours](https://www.gregorykapfhammer.com/schedule/) if you
have questions

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekfive/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week Five: Runtime Analysis through Experimental Evaluation](../../slides/weekfive/)
